'use strict'
/**
 * scripts/build-texture.js — embed the official /operator background assets (and
 * the round arrow of its filter dropdown) into client.js as data URIs.
 *
 * SOURCE OF THE ASSETS (provenance, do not lose):
 *   All three are the official Arknights: Endfield site's own page backgrounds,
 *   served from its official CDN for the /operator route:
 *     https://web.hycdn.cn/endfield/official-v4/_next/static/media/<name>
 *   downloaded 2026-10-01; sha256 of the exact bytes committed under assets/:
 *
 *     endfield-block-bg.svg      16d0d6dcb24d1cdb2765a23d4db864dd7a5599a27d9b9f2ed34c72474b0f8675
 *     endfield-wave-bg.png       5a9efdd3ede79f2e4a7cf033e25b1716847d210f636e950db0fc5c870f6dcdac
 *     endfield-tape-wave-bg.png  66b0f225288d5c5b5b5415f64be56663500a51c24f093ab26c9da1a553c7a99e
 *
 *   official filenames: block-bg.f05eda37.svg, wave-bg.8955885a.png,
 *                       tape-wave-bg.2bce9fc0.png
 *
 *   Same CDN, same route, the /operator page's filter dropdown (official
 *   Dropdown component, CSS bundle 3a129342b9ac5e73.css), downloaded 2026-10-01:
 *
 *     endfield-dropdown-arrow.png  34b1690c75f0da184f93a8af0bd60144c842036918157ca0cf8fe4bd79cd1db2
 *
 *   official filename: arrow.592963ed.png (the round chevron of .Dropdown_arrow)
 *   Taken because the repository owner pointed at that dropdown as THE
 *   reference for the settings panel's control (2026-10).
 *
 *   The local download-source policy defaults to official channels only; these
 *   ARE official (the game's own site, its own CDN hosts no third-party code),
 *   and taking them was explicitly instructed by the repository owner
 *   ("沿用官方"). Registered in README 素材归属 as well.
 *
 * WHAT THIS SCRIPT DOES. The SVG is editor-clean already (163 bytes: one <path>
 * with a 2px stroke), but it still goes through the same minimize pass the
 * emblem uses so the two pipelines stay one shape. The two PNGs are embedded
 * BYTE-FOR-BYTE (no re-encoding, no quantization, no downscaling) — the point of
 * "沿用官方" is that what ships is exactly what the site ships, not a
 * re-compression of it. Sizes: 17,084 B and 37,025 B -> ~72KB base64 total; the
 * dropdown arrow adds 874 B.
 *
 * Markers, same splice contract as build-emblem.js:
 *   node scripts/build-texture.js          # rewrite the marked region in client.js
 *   node scripts/build-texture.js --check  # exit 1 if client.js drifted
 */
const fs = require('fs')
const path = require('path')
const crypto = require('crypto')

const ROOT = path.join(__dirname, '..')
const CLIENT = path.join(ROOT, 'client.js')
const BEGIN = '/* EDGE_TEX_BEGIN (generated by scripts/build-texture.js — do not edit by hand) */'
const END = '/* EDGE_TEX_END */'
const checkOnly = process.argv.includes('--check')

/* Each entry: committed file, its pinned sha256, the CSS custom property it
   becomes, and the token the CSS reads it through. */
const ASSETS = [
  {
    file: 'endfield-block-bg.svg',
    sha256: '16d0d6dcb24d1cdb2765a23d4db864dd7a5599a27d9b9f2ed34c72474b0f8675',
    prop: '--edge-tex-grid-mask',
    kind: 'svg',
    note: 'engineering grid tile (viewBox 217x217, 2px stroke)',
  },
  {
    file: 'endfield-wave-bg.png',
    sha256: '5a9efdd3ede79f2e4a7cf033e25b1716847d210f636e950db0fc5c870f6dcdac',
    prop: '--edge-tex-wave',
    kind: 'png',
    note: '627x461 stepped wave, used top-right',
  },
  {
    file: 'endfield-tape-wave-bg.png',
    sha256: '66b0f225288d5c5b5b5415f64be56663500a51c24f093ab26c9da1a553c7a99e',
    prop: '--edge-tex-tape',
    kind: 'png',
    note: '946x216 wave band, used as the centre strip',
  },
  {
    file: 'endfield-dropdown-arrow.png',
    sha256: '34b1690c75f0da184f93a8af0bd60144c842036918157ca0cf8fe4bd79cd1db2',
    prop: '--edge-dd-arrow',
    kind: 'png',
    note: '97x96 round chevron of the official filter dropdown',
  },
]

/* Same minimize pass as build-emblem.js: drop the prolog/comments, rebuild the
   root with only the default namespace + viewBox, collapse whitespace. */
const minimizeSvg = (src) => {
  let s = src
  s = s.replace(/<\?xml[^>]*\?>/g, '')
  s = s.replace(/<!--[\s\S]*?-->/g, '')
  const vb = s.match(/viewBox="([^"]+)"/)
  if (!vb) throw new Error('no viewBox in the source SVG — cannot rebuild the root')
  s = s.replace(/<svg[\s\S]*?>/, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb[1]}">`)
  s = s.replace(/\s(id|class)="[^"]*"/g, '')
  s = s.replace(/<g\s*>/g, '<g>')
  s = s.replace(/\s+/g, ' ').replace(/\s*<\s*/g, '<').replace(/\s*>\s*/g, '>').trim()
  if (!/^<svg[\s\S]*<\/svg>$/.test(s)) throw new Error('minimized SVG failed its shape sanity check')
  return s
}

const main = () => {
  const parts = []
  for (const a of ASSETS) {
    const p = path.join(ROOT, 'assets', a.file)
    const raw = fs.readFileSync(p)
    const sha = crypto.createHash('sha256').update(raw).digest('hex')
    if (sha !== a.sha256) {
      throw new Error(`${a.file} sha256 drifted\n  expected ${a.sha256}\n  actual   ${sha}\n`
        + '  The upstream file changed (or the local copy did). Verify the new bytes against the\n'
        + '  official CDN URL before updating this pin — see README 素材归属.')
    }
    const payload = a.kind === 'svg' ? Buffer.from(minimizeSvg(raw.toString('utf8')), 'utf8') : raw
    const mime = a.kind === 'svg' ? 'image/svg+xml' : 'image/png'
    const uri = `data:${mime};base64,` + payload.toString('base64')
    parts.push({
      prop: a.prop,
      uri,
      line: `${a.file} (${a.note}) — ${raw.length}B raw, ${Math.round(uri.length / 1024)}KB base64, sha256 ${a.sha256.slice(0, 16)}…`,
    })
  }
  const block = BEGIN + '\n' +
    parts.map((p) => `  /* ${p.line} */\n  body { ${p.prop}: url("${p.uri}"); }`).join('\n') + '\n' +
    '  ' + END

  const src = fs.readFileSync(CLIENT, 'utf8')
  const beginIdx = src.indexOf(BEGIN)
  const endIdx = src.indexOf(END)
  if (beginIdx < 0 || endIdx < 0 || endIdx < beginIdx) {
    throw new Error('EDGE_TEX markers missing from client.js — see the background-texture CSS block')
  }
  const next = src.slice(0, beginIdx) + block + src.slice(endIdx + END.length)
  const total = parts.reduce((n, p) => n + p.uri.length, 0)
  if (next === src) {
    console.log(`ok       background texture unchanged (${parts.length} assets, ${Math.round(total / 1024)}KB base64)`)
    return
  }
  if (checkOnly) {
    console.error('DRIFTED  client.js texture region — run: node scripts/build-texture.js')
    process.exitCode = 1
    return
  }
  fs.writeFileSync(CLIENT, next)
  console.log(`updated  client.js background texture (${parts.length} assets, ${Math.round(total / 1024)}KB base64)`)
}

main()
