'use strict'
/**
 * scripts/build-logo.js — embed the hero logo's two alpha masks into client.js.
 *
 * SOURCE OF THE ASSET (provenance, do not lose):
 *   The artwork is the 「终末地标识 3」 sticker of the summer series (定格今夏) on the
 *   official Bilibili toy page for the 森空岛 × 优衣库 2026 collaboration:
 *     page    https://www.bilibili.com/toy/skland-uniqlo-2026/index.html
 *     asset   https://www.bilibiliytoy.com/toy/skland-uniqlo-2026/25109419164672-v10984/
 *               assets/stickers/summer/logo-03.png?v=10
 *   Downloaded 2026-10-01 from that official host (the only resolution it serves:
 *   1024x458 RGBA PNG, sha256 ee4fcfbd547e50202550d12bdd27934c608f3c8455d1242020b3e431c70dc966).
 *   The untouched bytes are kept at assets/hero-logo-3-summer.png. The artwork is
 *   Hypergryph brand art — the same fan-use status as every other brand asset in
 *   this repository (see README 素材归属); adopting it here was ordered by the
 *   repository owner.
 *
 * WHY TWO MASKS AND NOT THE COLOURED SVG ITSELF.
 *   The sticker is three flat colours (body #ffe01d, hatched step #f4d73e, wordmark
 *   #d2d3d4) and reads correctly only on a dark page: on the light theme's cream
 *   paper #d2d3d4 measures 1.2:1. Painting the artwork through an ALPHA MASK lets the
 *   stylesheet own the colours, so each scheme can carry values measured against the
 *   surface it really lands on (test/hero-logo.test.js enforces the bars) instead of
 *   baking a dark-only asset into the sheet. It is also 20x smaller: the traced
 *   outline + wordmark are 6.6KB of SVG, where the full three-colour vector is 197KB.
 *
 * HOW THE MASKS WERE PRODUCED (reproducible; potrace is not a build dependency, so
 * the traced output is checked in rather than regenerated here):
 *   1. classify every pixel of hero-logo-3-summer.png by nearest of the three
 *      colours above, keeping alpha >= 128 (the PNG is anti-aliased);
 *   2. write two P4 bitmaps — the BODY is the union of #ffe01d and #f4d73e (a
 *      union, not the base colour alone: the hatching is drawn by the stylesheet,
 *      and tracing the two separately left sub-pixel white seams between them),
 *      the INK is #d2d3d4;
 *   3. potrace -s (1:1, no upscaling: the mark is never painted wider than its
 *      1024px source) — one path per mask.
 *   The hatched step is NOT traced. It is a rigid line family measured off the
 *   artwork: x + 1.73y = const, period 28.20px along x, 39.7% of it hatched, i.e. a
 *   150deg repeating-linear-gradient, which is both exact and size-independent.
 *
 * Pure Node, no dependencies. Same marker-block splice contract as build-emblem.js:
 *   node scripts/build-logo.js          # rewrite the marked region in client.js
 *   node scripts/build-logo.js --check  # exit 1 if client.js drifted
 */
const fs = require('fs')
const path = require('path')

const ROOT = path.join(__dirname, '..')
const BODY_SRC = path.join(ROOT, 'assets', 'hero-logo-body.svg')
const INK_SRC = path.join(ROOT, 'assets', 'hero-logo-ink.svg')
const CLIENT = path.join(ROOT, 'client.js')
const BEGIN = '/* HERO_LOGO_BEGIN (generated by scripts/build-logo.js — do not edit by hand) */'
const END = '/* HERO_LOGO_END */'
const checkOnly = process.argv.includes('--check')

/* ---- strip the potrace wrapper down to a minimal single-line SVG ----
   A CSS mask needs the paths' ALPHA and nothing else, so the <metadata> block, the
   DOCTYPE, the pt-sized width/height, the fill and the editor attributes all go.
   The <g transform> is load-bearing (potrace emits 1/10px units, y-up) and stays. */
const minimizeSvg = (src) => {
  let s = src
  s = s.replace(/<\?xml[^>]*\?>/g, '')
  s = s.replace(/<!DOCTYPE[^>]*>/g, '')
  s = s.replace(/<metadata>[\s\S]*?<\/metadata>/g, '')
  s = s.replace(/<!--[\s\S]*?-->/g, '')
  const vb = s.match(/viewBox="([^"]+)"/)
  if (!vb) throw new Error('no viewBox in the source SVG — cannot rebuild the root')
  s = s.replace(/<svg[\s\S]*?>/, '<svg xmlns="http://www.w3.org/2000/svg" viewBox="' + vb[1] + '">')
  s = s.replace(/\s(fill|stroke)="[^"]*"/g, '')
  s = s.replace(/\s(id|class)="[^"]*"/g, '')
  s = s.replace(/\s+/g, ' ').replace(/\s*<\s*/g, '<').replace(/\s*>\s*/g, '>').trim()
  if (!/<path/.test(s) || !s.endsWith('</svg>')) {
    throw new Error('minimized SVG failed its shape sanity check')
  }
  return s
}

const uri = (svg) => 'data:image/svg+xml;base64,' + Buffer.from(svg, 'utf8').toString('base64')

const main = () => {
  const bodySvg = minimizeSvg(fs.readFileSync(BODY_SRC, 'utf8'))
  const inkSvg = minimizeSvg(fs.readFileSync(INK_SRC, 'utf8'))
  const bodyUri = uri(bodySvg)
  const inkUri = uri(inkSvg)
  const src = fs.readFileSync(CLIENT, 'utf8')
  const beginIdx = src.indexOf(BEGIN)
  const endIdx = src.indexOf(END)
  if (beginIdx < 0 || endIdx < 0 || endIdx < beginIdx) {
    throw new Error('HERO_LOGO markers missing from client.js — see the hero logo CSS block')
  }
  /* Both declarations MUST live inside ONE body{} rule: a bare top-level declaration
     is invalid CSS and the parser's error recovery then eats the next rule's
     selector (the emblem block shipped that bug once — check.js pins the shape). */
  const kb = (s) => Math.round(s.length / 1024) + 'KB'
  const block = BEGIN + '\n' +
    '  /* Hero brand mark, alpha masks only — the colours come from the stylesheet so\n' +
    '     each scheme can carry measured values (see the [data-endfield-hero-logo]\n' +
    '     block). Body outline ' + bodySvg.length + ' bytes / ' + kb(bodyUri) + ' base64,\n' +
    '     wordmark ' + inkSvg.length + ' bytes / ' + kb(inkUri) + ' base64.\n' +
    '     Regenerate: node scripts/build-logo.js */\n' +
    '  body {\n' +
    '    --edge-hero-logo-body-mask: url("' + bodyUri + '");\n' +
    '    --edge-hero-logo-ink-mask: url("' + inkUri + '");\n' +
    '  }\n' +
    '  ' + END
  const next = src.slice(0, beginIdx) + block + src.slice(endIdx + END.length)
  if (next === src) {
    console.log('ok       hero logo masks unchanged (' + bodySvg.length + ' + ' + inkSvg.length + ' bytes SVG, ' + kb(bodyUri) + ' + ' + kb(inkUri) + ' base64)')
    return
  }
  if (checkOnly) {
    console.error('DRIFTED  client.js hero-logo region — run: node scripts/build-logo.js')
    process.exitCode = 1
    return
  }
  fs.writeFileSync(CLIENT, next)
  console.log('updated  client.js hero logo masks (' + bodySvg.length + ' + ' + inkSvg.length + ' bytes SVG, ' + kb(bodyUri) + ' + ' + kb(inkUri) + ' base64)')
}

main()
