'use strict'
/**
 * scripts/build-emblem.js — embed the watermark logo mask into client.js.
 *
 * SOURCE OF THE ASSET (provenance, do not lose):
 *   assets/endfield-industries.svg is the vectorized Endfield Industries emblem
 *   (barcode wordmark + inverted triangle) from the open fan repository
 *     https://github.com/Yue-plus/endfield_icons  (svg/endfield-industries.svg)
 *   downloaded 2026-09-30; original sha256
 *     3e2af120ec6c86d2132448e7fbd4264b50e7258276c1beabb2bf3fa666200025
 *   The repository declares MIT, but the underlying artwork is Hypergryph
 *   brand art — same fan-use status as every other brand-derived asset here
 *   (see README 素材归属). Adoption of this third-party source was explicitly
 *   approved by the repository owner (the local download-source policy exempts
 *   this one file by name).
 *
 * WHAT THIS SCRIPT DOES. The downloaded SVG carries editor metadata (Adobe
 * Illustrator generator comment, Inkscape/Sodipodi namespace declarations,
 * element ids, pretty-print whitespace) that is dead weight in a data URI. The
 * build strips all of that to a single-line minimal SVG and splices it into
 * client.js as --edge-emblem, used as a CSS MASK in ALPHA mode: the paths'
 * own alpha channel IS the shape, so the default fill (black) paints the mark
 * with currentColor at any scale — vector, so it is crisp at every zoom and
 * devicePixelRatio (the previous pipeline thresholded the official blurred
 * PNG at 755px, which was raster-capped by comparison).
 *
 * Pure Node, no dependencies. Same marker-block splice contract as before:
 *   node scripts/build-emblem.js          # rewrite the marked region in client.js
 *   node scripts/build-emblem.js --check  # exit 1 if client.js drifted
 */
const fs = require('fs')
const path = require('path')
const zlib = require('zlib') // kept: crc/deflate helpers removed with the PNG pipeline

const ROOT = path.join(__dirname, '..')
const SRC = path.join(ROOT, 'assets', 'endfield-industries.svg')
const CLIENT = path.join(ROOT, 'client.js')
const BEGIN = '/* EMBLEM_MASK_BEGIN (generated by scripts/build-emblem.js — do not edit by hand) */'
const END = '/* EMBLEM_MASK_END */'
const checkOnly = process.argv.includes('--check')

/* ---- strip editor metadata down to a minimal single-line SVG ---- */
const minimizeSvg = (src) => {
  let s = src
  // XML prolog and the Illustrator generator comment (comments may span lines).
  s = s.replace(/<\?xml[^>]*\?>/g, '')
  s = s.replace(/<!--[\s\S]*?-->/g, '')
  // Rebuild the root element: keep ONLY the default namespace and the viewBox.
  const vb = s.match(/viewBox="([^"]+)"/)
  if (!vb) throw new Error('no viewBox in the source SVG — cannot rebuild the root')
  const open = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb[1]}">`
  s = s.replace(/<svg[\s\S]*?>/, open)
  // Group/shape ids and editor attributes are inert here; drop them.
  s = s.replace(/\s(id|class)="[^"]*"/g, '')
  s = s.replace(/<g\s*>/g, '<g>')
  // Path data separates coordinates with whitespace; collapse ALL whitespace to
  // single spaces (safe for d/points values) and drop inter-tag padding.
  s = s.replace(/\s+/g, ' ').replace(/\s*<\s*/g, '<').replace(/\s*>\s*/g, '>').trim()
  if (!/<path/.test(s) || !s.endsWith('</svg>')) {
    throw new Error('minimized SVG failed its shape sanity check')
  }
  return s
}

/* ---- splice the data URI into client.js between the markers ---- */
const main = () => {
  const svg = minimizeSvg(fs.readFileSync(SRC, 'utf8'))
  const uri = 'data:image/svg+xml;base64,' + Buffer.from(svg, 'utf8').toString('base64')
  const src = fs.readFileSync(CLIENT, 'utf8')
  const beginIdx = src.indexOf(BEGIN)
  const endIdx = src.indexOf(END)
  if (beginIdx < 0 || endIdx < 0 || endIdx < beginIdx) {
    throw new Error('EMBLEM_MASK markers missing from client.js — see the watermark CSS block')
  }
  /* The declaration MUST live inside a body{} rule: a bare top-level
     declaration is invalid CSS, and the parser's error recovery then swallows
     the NEXT rule's selector as its block (measured: it ate
     [data-endfield-contour] and the sheet silently lost it). check.js pins
     this shape. */
  const block = BEGIN + '\n' +
    `  /* Vector emblem mask (Yue-plus/endfield_icons vectorization of the official\n` +
    `     Hypergryph mark; see scripts/build-emblem.js for provenance). Minimized\n` +
    `     SVG ${svg.length} bytes / ${Math.round(uri.length / 1024)}KB base64. Alpha mask:\n` +
    `     the paths' own alpha is the shape. Regenerate: node scripts/build-emblem.js */\n` +
    `  body { --edge-emblem: url("${uri}"); }\n` +
    '  ' + END
  const next = src.slice(0, beginIdx) + block + src.slice(endIdx + END.length)
  if (next === src) {
    console.log(`ok       emblem mask unchanged (minimized SVG ${svg.length} bytes, ${Math.round(uri.length / 1024)}KB base64)`)
    return
  }
  if (checkOnly) {
    console.error('DRIFTED  client.js emblem region — run: node scripts/build-emblem.js')
    process.exitCode = 1
    return
  }
  fs.writeFileSync(CLIENT, next)
  console.log(`updated  client.js emblem mask (minimized SVG ${svg.length} bytes, ${Math.round(uri.length / 1024)}KB base64)`)
}

main()
